version: '3'
services:

  agent-test:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    image: agent
    container_name: agent-test
    restart: unless-stopped
    working_dir: /app
networks:
  default:
    external:
      name: challenge-ml